### ISSUE TITLE
[Mere-uspesnosti.pdf] Konstrukcija ROC krivulje

### ISSUE THREAD

**Issue by mjazbc** [BlazZupan/ozp-zapiski#4]
Mislim, da se je v poglavju 5.1.1 v opis postopka za konstrukcijo ROC prikradla napaka. Glede na to, da os y predstavlja true positive, os x pa false positive rate, se moramo pri risanju pomakniti za **n+ razdelkov navzgor in n- razdelkov v desno** in ne obratno, kot je napisano v točki 4.

**Comment by BlazZupan** [comment]
Pravilno, hvala, ravno popravljam. (+3)
